const mongoose = require('mongoose');
const config = require('../config');
const TramiteCatalogo = require('../models/tramiteCatalogo.model');
const { prepararPayload } = require('../services/tramiteCatalogo.service');

const tramites = [
  {
    slug: 'habilitacion-comercial',
    titulo: 'Habilitacion comercial',
    resumen: 'Inicia la habilitacion de un nuevo comercio, industria o actividad asimilable.',
    descripcion: 'Permite solicitar la habilitacion municipal para desarrollar una actividad comercial en Villa Gesell.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['habilitar', 'comercio', 'local', 'negocio', 'rubro', 'apertura'],
    sinonimos: ['abrir comercio', 'alta comercial', 'habilitacion de local', 'permiso comercial'],
    requisitosResumen: ['DNI', 'CUIT', 'documentacion del inmueble', 'constancias impositivas', 'documentacion tecnica segun rubro'],
    costoResumen: 'El area informa los costos administrativos durante la revision.',
    demoraEstimada: 'Sujeto a revision documental e inspeccion.',
    urlInformacion: '/comercio/tramites',
    urlInicio: '/comercio/tramites/form?tramite=Habilitaci%C3%B3n',
    urlConsultaEstado: '/comercio/consulta_tramite',
    icono: 'shop',
    destacado: true,
    prioridad: 100,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 4 },
      { key: 'tema', values: ['comercio'], weight: 5 },
      { key: 'accionComercio', values: ['abrir'], weight: 6 },
    ],
  },
  {
    slug: 'baja-comercial',
    titulo: 'Baja comercial',
    resumen: 'Solicita la baja de una habilitacion comercial existente.',
    descripcion: 'Sirve para finalizar una habilitacion comercial y obtener la constancia correspondiente.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['baja', 'cerrar', 'cierre', 'finalizar', 'habilitacion', 'comercio'],
    sinonimos: ['cerrar comercio', 'dar de baja local', 'baja de habilitacion'],
    requisitosResumen: ['DNI', 'libres deuda', 'documentacion del inmueble', 'documentacion de representacion si corresponde'],
    costoResumen: 'El area informa los costos administrativos durante la revision.',
    demoraEstimada: 'Sujeto a verificacion del Departamento Comercio.',
    urlInformacion: '/comercio/tramites',
    urlInicio: '/comercio/tramites/form?tramite=Baja',
    urlConsultaEstado: '/comercio/consulta_tramite',
    icono: 'x-circle',
    destacado: true,
    prioridad: 90,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 4 },
      { key: 'tema', values: ['comercio'], weight: 5 },
      { key: 'accionComercio', values: ['cerrar'], weight: 8 },
    ],
  },
  {
    slug: 'renovacion-comercial',
    titulo: 'Renovacion comercial',
    resumen: 'Renova una habilitacion comercial cuando corresponde actualizar la documentacion.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['renovar', 'renovacion', 'habilitacion', 'comercio', 'legajo'],
    sinonimos: ['renovar comercio', 'renovar habilitacion'],
    requisitosResumen: ['Numero de legajo', 'DNI', 'constancias impositivas', 'documentacion del inmueble'],
    urlInformacion: '/comercio/tramites',
    urlInicio: '/comercio/tramites/form?tramite=Renovaci%C3%B3n',
    urlConsultaEstado: '/comercio/consulta_tramite',
    icono: 'arrow-repeat',
    prioridad: 70,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 3 },
      { key: 'tema', values: ['comercio'], weight: 5 },
      { key: 'accionComercio', values: ['renovar'], weight: 8 },
    ],
  },
  {
    slug: 'reempadronamiento-comercial',
    titulo: 'Reempadronamiento comercial',
    resumen: 'Actualiza datos y documentacion de una habilitacion comercial vigente.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['reempadronar', 'reempadronamiento', 'actualizar', 'comercio', 'legajo'],
    sinonimos: ['actualizar comercio', 'actualizacion comercial'],
    requisitosResumen: ['Numero de legajo', 'DNI', 'declaracion jurada', 'constancias impositivas'],
    urlInformacion: '/comercio/tramites',
    urlInicio: '/comercio/tramites/form?tramite=Reempadronamiento',
    urlConsultaEstado: '/comercio/consulta_tramite',
    icono: 'clipboard-check',
    prioridad: 65,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 3 },
      { key: 'tema', values: ['comercio'], weight: 5 },
      { key: 'accionComercio', values: ['actualizar'], weight: 8 },
    ],
  },
  {
    slug: 'cambio-titular-comercial',
    titulo: 'Cambio de titular comercial',
    resumen: 'Solicita el cambio de titularidad de una habilitacion comercial.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['cambio titular', 'titularidad', 'transferencia', 'comercio'],
    sinonimos: ['cambiar titular', 'pasar comercio a otra persona'],
    requisitosResumen: ['Numero de legajo', 'documentacion del titular anterior', 'conformidad de cambio', 'constancias impositivas'],
    urlInformacion: '/comercio/tramites',
    urlInicio: '/comercio/tramites/form?tramite=Cambio%20de%20Titular',
    urlConsultaEstado: '/comercio/consulta_tramite',
    icono: 'person-lines-fill',
    prioridad: 60,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 3 },
      { key: 'tema', values: ['comercio'], weight: 5 },
      { key: 'accionComercio', values: ['cambiar titular'], weight: 8 },
    ],
  },
  {
    slug: 'consulta-estado-tramite-comercial',
    titulo: 'Consulta de estado de tramite comercial',
    resumen: 'Consulta el estado de una solicitud comercial con el numero de tramite.',
    area: 'comercio',
    categoria: 'Consultas',
    audiencia: ['contribuyente', 'comerciante'],
    modalidad: 'online',
    palabrasClave: ['consulta', 'estado', 'seguimiento', 'numero de tramite', 'expediente'],
    sinonimos: ['ver estado', 'consultar tramite', 'seguimiento de tramite'],
    requisitosResumen: ['Numero de tramite'],
    urlInformacion: '/comercio/consulta_tramite',
    urlInicio: '/comercio/consulta_tramite',
    icono: 'search',
    destacado: true,
    prioridad: 95,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['consultar'], weight: 9 },
      { key: 'tema', values: ['comercio'], weight: 3 },
    ],
  },
  {
    slug: 'abierto-anual-comercios',
    titulo: 'Abierto Anual de comercios',
    resumen: 'Carga las facturas requeridas para el beneficio de Abierto Anual.',
    area: 'comercio',
    categoria: 'Comercios',
    audiencia: ['comerciante'],
    modalidad: 'online',
    palabrasClave: ['abierto anual', 'facturas', 'beneficio', 'comercio', 'tickets'],
    sinonimos: ['cargar facturas comercio', 'beneficio abierto anual'],
    requisitosResumen: ['CUIT', 'numero de legajo', 'facturas de los periodos solicitados'],
    urlInformacion: '/comercio/abierto_anual',
    urlInicio: '/comercio/abierto_anual',
    icono: 'calendar-check',
    destacado: true,
    prioridad: 80,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 2 },
      { key: 'tema', values: ['comercio'], weight: 4 },
      { key: 'accionComercio', values: ['abierto anual'], weight: 9 },
    ],
  },
  {
    slug: 'turnos-inspeccion-comercio',
    titulo: 'Turnos para inspeccion de comercio',
    resumen: 'Solicita turno para inspeccion comercial cuando el area lo indique.',
    area: 'comercio',
    categoria: 'Turnos',
    audiencia: ['comerciante'],
    modalidad: 'online',
    palabrasClave: ['turno', 'inspeccion', 'comercio', 'habilitacion'],
    sinonimos: ['sacar turno comercio', 'turno inspeccion comercial'],
    requisitosResumen: ['Numero de tramite autorizado por el Departamento Comercio'],
    urlInformacion: '/comercio/turnos',
    urlInicio: '/comercio/turnos',
    icono: 'clock',
    prioridad: 50,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['turno'], weight: 9 },
      { key: 'tema', values: ['comercio'], weight: 4 },
    ],
  },
  {
    slug: 'reclamo-pago-doble',
    titulo: 'Reclamo por pago doble',
    resumen: 'Informa un pago doble de tasa urbana para solicitar acreditacion de saldo.',
    area: 'recaudaciones',
    categoria: 'Reclamos',
    audiencia: ['contribuyente'],
    modalidad: 'online',
    palabrasClave: ['pago doble', 'reclamo', 'saldo', 'tasa urbana', 'acreditacion'],
    sinonimos: ['pague dos veces', 'doble pago', 'devolucion tasa', 'credito por pago'],
    requisitosResumen: ['DNI', 'comprobantes de pago', 'acreditacion de titularidad'],
    urlInformacion: '/recaudaciones/pagos_dobles',
    urlInicio: '/recaudaciones/pagos_dobles/form',
    urlConsultaEstado: '/recaudaciones/pagos_dobles',
    icono: 'receipt-cutoff',
    destacado: true,
    prioridad: 90,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['reclamar'], weight: 7 },
      { key: 'tema', values: ['tasa', 'inmueble'], weight: 4 },
      { key: 'problemaPago', values: ['pago doble'], weight: 9 },
    ],
  },
  {
    slug: 'descargar-tasa-automotor',
    titulo: 'Descargar Tasa Automotor',
    resumen: 'Consulta y descarga boletas de automotores por dominio.',
    area: 'recaudaciones',
    categoria: 'Tasas',
    audiencia: ['contribuyente'],
    modalidad: 'online',
    palabrasClave: ['automotor', 'patente', 'dominio', 'boleta', 'pagar', 'tasa'],
    sinonimos: ['patente municipal', 'boleta auto', 'tasa vehiculo', 'pagar automotor'],
    requisitosResumen: ['Dominio del vehiculo'],
    urlInformacion: '/recaudaciones/tasa-automotor',
    urlInicio: '/recaudaciones/tasa-automotor',
    icono: 'car-front',
    destacado: true,
    prioridad: 100,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['pagar', 'descargar'], weight: 7 },
      { key: 'tema', values: ['automotor'], weight: 9 },
    ],
  },
  {
    slug: 'descargar-tasa-urbana',
    titulo: 'Descargar Tasa Urbana',
    resumen: 'Consulta y descarga boletas de Tasa Urbana por partida.',
    area: 'recaudaciones',
    categoria: 'Tasas',
    audiencia: ['contribuyente'],
    modalidad: 'online',
    palabrasClave: ['urbana', 'partida', 'inmueble', 'boleta', 'pagar', 'tasa'],
    sinonimos: ['servicios urbanos', 'boleta municipal', 'tasa inmueble', 'pagar partida'],
    requisitosResumen: ['Numero de partida municipal'],
    urlInformacion: '/recaudaciones/tasa-urbana',
    urlInicio: '/recaudaciones/tasa-urbana',
    icono: 'building',
    destacado: true,
    prioridad: 100,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['pagar', 'descargar'], weight: 7 },
      { key: 'tema', values: ['inmueble', 'tasa'], weight: 9 },
    ],
  },
  {
    slug: 'inscripcion-proveedores',
    titulo: 'Inscripcion de proveedores',
    resumen: 'Informacion para inscribirse como proveedor municipal.',
    area: 'compras',
    categoria: 'Proveedores',
    audiencia: ['proveedor', 'contribuyente'],
    modalidad: 'mixto',
    palabrasClave: ['proveedor', 'inscripcion', 'compras', 'suministros', 'municipal'],
    sinonimos: ['alta proveedor', 'ser proveedor municipal', 'registro proveedor'],
    requisitosResumen: ['Documentacion societaria o personal segun corresponda'],
    urlInformacion: '/compras/proveedores',
    urlInicio: '/compras/proveedores',
    icono: 'briefcase',
    prioridad: 70,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar'], weight: 4 },
      { key: 'tema', values: ['proveedor', 'compras'], weight: 9 },
    ],
  },
  {
    slug: 'licitaciones-publicas',
    titulo: 'Licitaciones publicas',
    resumen: 'Consulta pliegos y notas aclaratorias de Compras y Suministros.',
    area: 'compras',
    categoria: 'Licitaciones',
    audiencia: ['proveedor', 'contribuyente'],
    modalidad: 'externo',
    palabrasClave: ['licitacion', 'pliegos', 'compras', 'suministros', 'ofertas'],
    sinonimos: ['concursos de precios', 'compras publicas'],
    requisitosResumen: ['Consultar condiciones de cada licitacion publicada'],
    urlInformacion: 'https://hacienda.gesell.gob.ar/compras-y-suministros.html',
    urlInicio: 'https://hacienda.gesell.gob.ar/compras-y-suministros.html',
    icono: 'receipt',
    prioridad: 55,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['consultar'], weight: 4 },
      { key: 'tema', values: ['compras', 'proveedor'], weight: 7 },
    ],
  },
  {
    slug: 'declaracion-jurada-fallecidos',
    titulo: 'Declaracion jurada de fallecidos',
    resumen: 'Gestiona fallecidos y declaraciones juradas mensuales de funerarias.',
    area: 'cementerio',
    categoria: 'Funerarias',
    audiencia: ['funeraria'],
    modalidad: 'online',
    palabrasClave: ['cementerio', 'fallecidos', 'defuncion', 'funeraria', 'declaracion jurada'],
    sinonimos: ['certificado defuncion', 'declarar fallecido', 'registro funeraria'],
    requisitosResumen: ['Usuario habilitado para funeraria', 'datos del fallecido', 'comprobantes y certificados requeridos'],
    urlInformacion: '/cementerio/certificado_defuncion',
    urlInicio: '/cementerio/certificado_defuncion',
    icono: 'file-earmark-medical',
    prioridad: 45,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['iniciar', 'consultar'], weight: 3 },
      { key: 'tema', values: ['cementerio', 'funeraria'], weight: 9 },
    ],
  },
  {
    slug: 'pagos-arvige',
    titulo: 'Pagos ARVIGE',
    resumen: 'Accede al portal externo de pagos municipales.',
    area: 'recaudaciones',
    categoria: 'Pagos',
    audiencia: ['contribuyente'],
    modalidad: 'externo',
    palabrasClave: ['pagar', 'pago', 'arvige', 'tasas', 'boletas'],
    sinonimos: ['portal de pagos', 'pagar online', 'pagar tasa'],
    requisitosResumen: ['Datos de la boleta o cuenta a pagar'],
    urlInformacion: 'https://arvige.gob.ar/lpagos',
    urlInicio: 'https://arvige.gob.ar/lpagos',
    icono: 'cash-coin',
    destacado: true,
    prioridad: 85,
    estado: 'publicado',
    reglasAsistente: [
      { key: 'necesidad', values: ['pagar'], weight: 9 },
      { key: 'tema', values: ['tasa'], weight: 3 },
    ],
  },
];

(async () => {
  try {
    if (!config.MONGO_URL) {
      throw new Error('La variable MONGO_URL no esta configurada.');
    }

    await mongoose.connect(config.MONGO_URL, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    for (const tramite of tramites) {
      const payload = prepararPayload(tramite);
      await TramiteCatalogo.updateOne({ slug: payload.slug }, payload, { upsert: true, runValidators: true });
    }

    console.log(`Catalogo de tramites actualizado: ${tramites.length} registros.`);
    process.exit(0);
  } catch (error) {
    console.error('Error al inicializar catalogo de tramites:', error.message);
    process.exit(1);
  }
})();
